name: 🚀 Deploy Minecraft Server
on:
    push:
        branches:
            - main

jobs:
    minecraft-deploy:
        name: 🎮 Deploy Minecraft Server
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy to Azure VM
              run: |
                  ssh -o StrictHostKeyChecking=no azureuser@20.51.207.28 << 'EOF'
                  cd /home/azureuser/minecraft-server/
                  git pull origin main || { echo 'Git pull failed'; exit 1; }
                  # Stop Minecraft server
                  sudo systemctl stop minecraft-server.service || { echo 'Stop service failed'; exit 1; }
                  # Start Minecraft server
                  sudo systemctl start minecraft-server.service || { echo 'Start service failed'; exit 1; }
                  # Check the server status
                  sudo systemctl status minecraft-server.service || { echo 'Server status check failed'; exit 1; }
                  EOF
